version: '2'
services:
  # db:
  #   build: ./db
  #   volumes:
  #     - ./db/pgdata:/pgdata
  #   ports:
  #     - "5432"
  #   environment:
  #     - POSTGRES_USER=docker
  #     - POSTGRES_PASSWORD=docker
  #     - PGDATA=/pgdata

  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./api:/go/src/github.com/user/api-b2w-planetas/api
    ports:
      - "5000:10000"
    # links:
    #   - db


#http://localhost:5000/article/2
